version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  back:
    build: packages/back
    env_file: .env
    expose:
      - "${NODE_PORT}"
    links:
      - mongo
  front:
    build: packages/front
    expose:
      - "${FRONT_PORT}"
    links: 
      - back
  nginx:
    build: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    links:
      - front

