version: '3'
services:
  nginx:
    build: services/nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - front
    restart: always
  front:
    build: 
      context: packages/front
      args:
        FRONT_PORT: "${FRONT_PORT}"
    expose:
      - "${FRONT_PORT}"
    depends_on: 
      - back
    restart: always    
  back:
    build: 
      context: packages/back
      args:
        WAIT_FOR_IT: "mongo:${MONGO_PORT}"
    env_file: .env
    expose:
      - "${NODE_PORT}"
    depends_on:
      - mongo
    restart: always
    
  


